# Generated by Django 4.2.5 on 2023-12-14 19:49

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JeepneyDriver',
            fields=[
                ('id', models.CharField(default=base.models.generate_short_id, editable=False, max_length=4, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('route', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='driver_photo')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='driver_qrcodes')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_route', models.CharField(max_length=100)),
                ('to_route', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('routes', models.ManyToManyField(related_name='stations', to='base.route')),
                ('station_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('serving', 'Now Serving'), ('waiting', 'Waiting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=10, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.jeepneydriver')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.station')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
